MACRO(ADD_PRECOMPILED_HEADER PRECOMPILED_HEADER PRECOMPILED_SOURCE SRCS)
	IF (MSVC)
		GET_FILENAME_COMPONENT(PRECOMPILED_BASE_NAME ${PRECOMPILED_HEADER} NAME_WE)
		SET(PRECOMPILED_BINARY "${CMAKE_CURRENT_BINARY_DIR}/${PRECOMPILED_BASE_NAME}.pch")

		SET_SOURCE_FILES_PROPERTIES(${PRECOMPILED_SOURCE}
									PROPERTIES COMPILE_FLAGS "/Yc\"${PRECOMPILED_HEADER}\" /Fp\"${PRECOMPILED_BINARY}\""
									OBJECT_OUTPUTS "${PRECOMPILED_BINARY}")
		SET_SOURCE_FILES_PROPERTIES(${SRCS}
									PROPERTIES COMPILE_FLAGS "/Yu\"${PRECOMPILED_BINARY}\" /FI\"${PRECOMPILED_BINARY}\" /Fp\"${PRECOMPILED_BINARY}\""
                                    OBJECT_DEPENDS "${PRECOMPILED_BINARY}")  
	ENDIF (MSVC)
ENDMACRO(ADD_MSVC_PRECOMPILED_HEADER)
