SET (BULLET_PATHS    
   $ENV{PROGRAMFILES}/Bullet
   $ENV{PROGRAMFILES}/BULLET_PHYSICS
   $ENV{BULLETDIR}
   $ENV{BULLET_DIR}
)

IF (WIN32)
    SET (INCLUDE_PATH_PREFIX "")
ELSE (WIN32)
    SET (INCLUDE_PATH_PREFIX "bullet/")
ENDIF (WIN32)

SET (WANTED_MODULE_NAME     BulletMath)
SET (WANTED_INCLUDES        "${INCLUDE_PATH_PREFIX}LinearMath/btVector3.h")
SET (WANTED_LIBRARIES       linearmath bulletmath)
SET (WANTED_INCLUDES_PATH   ${BULLET_PATHS}) 
SET (WANTED_LIBRARIES_PATH  ${BULLET_PATHS}) 
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     BulletCollision)
SET (WANTED_INCLUDES        "${INCLUDE_PATH_PREFIX}btBulletCollisionCommon.h")
SET (WANTED_LIBRARIES       bulletcollision)
SET (WANTED_INCLUDES_PATH   ${BULLET_PATHS}) 
SET (WANTED_LIBRARIES_PATH  ${BULLET_PATHS}) 
INCLUDE (FindCommonModule)

SET (WANTED_MODULE_NAME     BulletDynamics)
SET (WANTED_INCLUDES        "${INCLUDE_PATH_PREFIX}btBulletDynamicsCommon.h")
SET (WANTED_LIBRARIES       bulletdynamics)
SET (WANTED_INCLUDES_PATH   ${BULLET_PATHS}) 
SET (WANTED_LIBRARIES_PATH  ${BULLET_PATHS}) 
INCLUDE (FindCommonModule)

# setup variables
IF ( BULLETMATH_FOUND AND BULLETCOLLISION_FOUND AND BULLETDYNAMICS_FOUND )
    SET (BULLET_FOUND TRUE)
ENDIF ( BULLETMATH_FOUND AND BULLETCOLLISION_FOUND AND BULLETDYNAMICS_FOUND )

# correct include path 
SET (Bullet_INCLUDE_DIR ${BulletMath_INCLUDE_DIR}/${INCLUDE_PATH_PREFIX})

SET (Bullet_LIBRARY
    ${BulletMath_LIBRARY}
    ${BulletCollision_LIBRARY}
    ${BulletDynamics_LIBRARY}
)

SET (Bullet_LIBRARIES 
    ${BulletMath_LIBRARIES}
    ${BulletCollision_LIBRARIES}
    ${BulletDynamics_LIBRARIES}
)

