SET ( GMATH_PATH
	${GMATH_PATH}
	"$ENV{GMATH_DIR}"
	"$ENV{PROGRAMFILES}/GraphicsMath"
	"${3RD_PARTY_DIRECTORY}/gmath"
	"${3RD_PARTY_DIRECTORY}/GraphicsMath "
)

# gmath
FIND_PATH ( 
	GMATH_INCLUDE_DIR
	gmath/Matrix.hpp
	PATH_SUFFIXES include
	PATHS ${GMATH_PATH}
)

IF (GMATH_INCLUDE_DIR)
	SET (GMATH_FOUND TRUE)
ENDIF (GMATH_INCLUDE_DIR)

IF (GMATH_FOUND AND NOT GMATH_FOUND_QUIETLY)
	MESSAGE(STATUS "Found gmath: ${GMATH_INCLUDE_DIR}/gmath")
ENDIF (GMATH_FOUND AND NOT GMATH_FOUND_QUIETLY)

